version: "3.7"

services:
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: ruby
    command: bundle exec rackup config.ru -o 0.0.0.0
    ports:
      - 9292:9292
    volumes:
      - type: bind
        source: .
        target: /sample-sinatra
    environment:
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: ""
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
