version: "3.7"

services:
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: ruby
    command: bundle exec rackup config.ru -o 0.0.0.0
    ports:
      - 9292:9292
      # - 4567:4567
    volumes:
      - type: bind
        source: .
        target: /sample-sinatra
    tty: true
    stdin_open: true
